/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADivider: typeof import('@arco-design/web-vue')['Divider']
    AInputNumber: typeof import('@arco-design/web-vue')['InputNumber']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    MeasurementProvider: typeof import('./src/components/MeasurementProvider.vue')['default']
    OverallResultProvider: typeof import('./src/components/OverallResultProvider.vue')['default']
    TemplateSelector: typeof import('./src/components/TemplateSelector.vue')['default']
  }
}
